
development:
  adapter: postgresql
  encoding: unicode
  database: codernuze_development
  pool: 5
  host: localhost
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: codernuze_test
  pool: 5
  host: localhost
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: codernuze_production
  pool: 5
  host: localhost
  username: postgres
  password:
